package com.ws.model;
// Generated 9 mai 2016 10:07:28 by Hibernate Tools 4.3.1.Final

/**
 * Affectation generated by hbm2java
 */
public class Affectation implements java.io.Serializable {

	private AffectationId id;
	private Bureau bureauByIdBureauDestination;
	private Bureau bureauByIdBureauSource;
	private Immobilisation immobilisation;

	public Affectation() {
	}

	public Affectation(AffectationId id, Bureau bureauByIdBureauDestination, Bureau bureauByIdBureauSource,
			Immobilisation immobilisation) {
		this.id = id;
		this.bureauByIdBureauDestination = bureauByIdBureauDestination;
		this.bureauByIdBureauSource = bureauByIdBureauSource;
		this.immobilisation = immobilisation;
	}

	public AffectationId getId() {
		return this.id;
	}

	public void setId(AffectationId id) {
		this.id = id;
	}

	public Bureau getBureauByIdBureauDestination() {
		return this.bureauByIdBureauDestination;
	}

	public void setBureauByIdBureauDestination(Bureau bureauByIdBureauDestination) {
		this.bureauByIdBureauDestination = bureauByIdBureauDestination;
	}

	public Bureau getBureauByIdBureauSource() {
		return this.bureauByIdBureauSource;
	}

	public void setBureauByIdBureauSource(Bureau bureauByIdBureauSource) {
		this.bureauByIdBureauSource = bureauByIdBureauSource;
	}

	public Immobilisation getImmobilisation() {
		return this.immobilisation;
	}

	public void setImmobilisation(Immobilisation immobilisation) {
		this.immobilisation = immobilisation;
	}

}
