package com.ws.model;
// Generated 9 mai 2016 10:07:28 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Famille generated by hbm2java
 */
public class Famille implements java.io.Serializable {

	private Integer id;
	private String designationFamille;
	private Set<SousFamille> sousFamilles = new HashSet<SousFamille>(0);

	public Famille() {
	}

	public Famille(String designationFamille) {
		this.designationFamille = designationFamille;
	}

	public Famille(String designationFamille, Set<SousFamille> sousFamilles) {
		this.designationFamille = designationFamille;
		this.sousFamilles = sousFamilles;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getDesignationFamille() {
		return this.designationFamille;
	}

	public void setDesignationFamille(String designationFamille) {
		this.designationFamille = designationFamille;
	}

	public Set<SousFamille> getSousFamilles() {
		return this.sousFamilles;
	}

	public void setSousFamilles(Set<SousFamille> sousFamilles) {
		this.sousFamilles = sousFamilles;
	}

}
