package com.ws.model;
// Generated 9 mai 2016 10:07:28 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * Service generated by hbm2java
 */
public class Service implements java.io.Serializable {

	private Integer idService;
	private String service;
	/*private int idChefService;*/
	private Set<Bureau> bureaus = new HashSet<Bureau>(0);

	public Service() {
	}

	public Service(String service/*, int idChefService*/) {
		this.service = service;
		//this.idChefService = idChefService;
	}

	public Service(String service,/* int idChefService,*/ Set<Bureau> bureaus) {
		this.service = service;
		//this.idChefService = idChefService;
		this.bureaus = bureaus;
	}

	public Integer getIdService() {
		return this.idService;
	}

	public void setIdService(Integer idService) {
		this.idService = idService;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	/*public int getIdChefService() {
		return this.idChefService;
	}

	public void setIdChefService(int idChefService) {
		this.idChefService = idChefService;
	}*/

	public Set<Bureau> getBureaus() {
		return this.bureaus;
	}

	public void setBureaus(Set<Bureau> bureaus) {
		this.bureaus = bureaus;
	}

}
