package com.ws.model;
// Generated 9 mai 2016 10:07:28 by Hibernate Tools 4.3.1.Final

import java.util.HashSet;
import java.util.Set;

/**
 * SousFamille generated by hbm2java
 */
public class SousFamille implements java.io.Serializable {

	private Integer idSousFamille;
	private Famille famille;
	private Set<Immobilisation> immobilisations = new HashSet<Immobilisation>(0);

	public SousFamille() {
	}

	public SousFamille(Famille famille) {
		this.famille = famille;
	}

	public SousFamille(Famille famille, Set<Immobilisation> immobilisations) {
		this.famille = famille;
		this.immobilisations = immobilisations;
	}

	public Integer getIdSousFamille() {
		return this.idSousFamille;
	}

	public void setIdSousFamille(Integer idSousFamille) {
		this.idSousFamille = idSousFamille;
	}

	public Famille getFamille() {
		return this.famille;
	}

	public void setFamille(Famille famille) {
		this.famille = famille;
	}

	public Set<Immobilisation> getImmobilisations() {
		return this.immobilisations;
	}

	public void setImmobilisations(Set<Immobilisation> immobilisations) {
		this.immobilisations = immobilisations;
	}

}
